aws_region         = "us-east-1"
environment        = "dev"
cluster_name       = "salon-dev-cluster"
cluster_version    = "1.28"
vpc_cidr           = "10.0.0.0/16"
availability_zones = ["us-east-1a", "us-east-1b"]
node_instance_types = ["t3.large"]
node_desired_size  = 2
node_min_size      = 1
node_max_size      = 5
